server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VeeRomanoff/config-environment.git
          repos:
            product-stock-service-repo:
              uri: https://github.com/VeeRomanoff/config-environment.git
              pattern: product-stock-service/*
              search-paths:
                - product-stock-service-config/{profile}